// Code generated by MockGen. DO NOT EDIT.
// Source: emailer.go

// Package emailer is a generated GoMock package.
package emailer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	notes "github.com/sergio-abreu/note-taking-app-backend-golang/domain/notes"
)

// MockEmailer is a mock of Emailer interface.
type MockEmailer struct {
	ctrl     *gomock.Controller
	recorder *MockEmailerMockRecorder
}

// MockEmailerMockRecorder is the mock recorder for MockEmailer.
type MockEmailerMockRecorder struct {
	mock *MockEmailer
}

// NewMockEmailer creates a new mock instance.
func NewMockEmailer(ctrl *gomock.Controller) *MockEmailer {
	mock := &MockEmailer{ctrl: ctrl}
	mock.recorder = &MockEmailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailer) EXPECT() *MockEmailerMockRecorder {
	return m.recorder
}

// SendNoteReminder mocks base method.
func (m *MockEmailer) SendNoteReminder(ctx context.Context, to string, note notes.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNoteReminder", ctx, to, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNoteReminder indicates an expected call of SendNoteReminder.
func (mr *MockEmailerMockRecorder) SendNoteReminder(ctx, to, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNoteReminder", reflect.TypeOf((*MockEmailer)(nil).SendNoteReminder), ctx, to, note)
}
